/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElIconMenu: typeof import('@element-plus/icons-vue')['Menu']
    ElIconPlus: typeof import('@element-plus/icons-vue')['Plus']
    ElIconSetting: typeof import('@element-plus/icons-vue')['Setting']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    MainPage: typeof import('./../src/renderer/src/components/MainPage.vue')['default']
    MindmapRenderer: typeof import('./../src/renderer/src/components/mindmap-renderer/mindmap-renderer.vue')['default']
    MSideBar: typeof import('./../src/renderer/src/components/mSideBar.vue')['default']
    MToolBar: typeof import('./../src/renderer/src/components/mToolBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
